README.md

Shifted gitter chat link to below #captain.

Update Readme.md : Added gitter chat link

---

README.md

I adjusted the header in the readme with the one in the instructions, updating the gitter badge at the top of the readme.

Issue #6: Updated gitter badge

---

LICENSE

Updated the copyright year in LICENSE file from 2017 to 2018

update copyright year to 2018 in LICENSE #11

---

src/vessel-charging/MissionParams.test.ts

Added MissionParams.test.ts in src/vessel-charging
This is for the open issue [#19](https://github.com/DAVFoundation/dav-js/issues/19) titled "Create tests for `vessel-charging/MissionParams` using jest." 
The tests verify that the serialize and deserialize work as intended
Set up the project on my machine and ran jest successfully

Created tests for `vessel-charging/MissionParams` #19

---

LICENSE

Add license file to project

---

README.md

Add license badge to README issues number #38 
People will know they are encouraged to contribute, fork, and extend this code

Add license badge to README #38

---

dist/Mission.test.js
src/Mission.test.ts

Removed unneeded beforeAll calls from Mission tests #44

---

src/Contracts.test.ts

remove unneeded beforeAll #43

---

README.md

Added gitter link to README

---

src/Bid.test.ts

Removing the assignment of BidParams so that it is just defined but not assigned.
https://github.com/DAVFoundation/dav-js/issues/50
In src/Bid.test.ts when bidParams is defined it was given a value (a new BidParams object). But that value was immediately being overwritten in the beforeEach function.
I tested this with `npm run jest`
Output:
`PASS  src/Bid.test.ts (12.583s)`
`Bid class`
`  requestCommitment method`
`   ✓ should return confirmation for already confirmed bid (349ms)`
`    ✓ should return confirmation after bidder had confirmed the bid (280ms)`
`    ✓ should return confirmation after bidder had confirmed the bid, and another bid confirmation was filtered (507ms)`
`  ✓ should throw due to kafka error in sendParams (420ms)`
`   ○ skipped 1 test`
`  accept method`
`   ✓ should …

Issue #50 DAVFoundation/dav-js/issues/50

---

README.md

I changed the link of the badge in the README
- [ x ] My code follows the code style of this project.
- [ x ] I have read the **CONTRIBUTING** document.

Improve gitter badge resolution in README #57

---

src/ride-hailing/NeedFilterParams.test.ts

Updated test for src/ride-hailing/NeedFilterParams.test.ts #55 
I made changes to the file NeedFilterParams.test.ts to accommodate more unit tests by updating the parameters to be dynamic by making them mutable.
#52 
First Timer, interested in contributing more to this repository.
This has been tested by running command `npm run jest`

Update test for src/ride-hailing/NeedFilterParams.test.ts 

---

src/vessel-charging/messages/ChargingArrivalMessageParams.test.ts

Created a Jest test to check that the serialize and deserialize methods return the expected object.
#23 
To validate expected results are returning correctly.
ran `npm run jest` and passes

Create tests for `vessel-charging/messages/ChargingArrivalMessageParams` using jest. #23

---

src/ride-hailing/BidParams.test.ts

Update vehicle details in tests

---

src/Bid.test.ts

Removed unneeded code to make it type messageParams
Already made the pull request before, but now it's with all the updated commits etc.
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.

Remove unneeded code (issue #66)

---

src/drone-delivery/NeedFilterParams.test.ts

Added a test for needFilterParams 
Added a test for needFilterParams 
#111 
When running `npm run jest'.All the tests passed

Add test for NeedFilterParams

---

src/drone-delivery/BidParams.test.ts

Added BidParams.test.ts for drone-delivery. File includes tests for serialize() and deserialize() methods.
Issue #98.
Issue #98.
Tested on Ubuntu 18.04.1. Node.js version 10.12.0. Run "npm run tslint" and "npm run jest" commands.

Add src/drone-delivery/BidParams.test.ts Issue #98

---

src/drone-charging/MissionParams.test.ts

Added src/drone-charging/MissionParams.test.ts.
#95.
This tests the serialize() and deserialiaze() methods of the drone-charging/MessageParams class.
I ran npm run jest which showed that all tests passed.

Fixes issue #95 - created tests for drone-charging mission parameters

---

src/ride-hailing/NeedParams.test.ts

Created tests for `ride-hailing/NeedParams` using jest.
I have added test cases for NeedParams in ride-hailing
https://github.com/DAVFoundation/dav-js/issues/22
Written for test coverage 
On local system 
- [x ] My code follows the code style of this project.

#22 Created tests for `ride-hailing/NeedParams` using jest.

---

src/ride-hailing/NeedFilterParams.test.ts

As per Issue #80, a successful test using Jest for _serialize_  function in `src/ride-hailing/NeedFilterParams.test.ts` has been added.
Issue: #80
<pre><b>Test Suites: </b><font color="#EF2929"><b>2 failed</b></font>, <font color="#8AE234"><b>33 passed</b></font>, 35 total
<b>Tests:       </b><font color="#FCE94F"><b>23 skipped</b></font>, <font color="#8AE234"><b>115 passed</b></font>, 138 total
<b>Snapshots:   </b>0 total
<b>Time:</b>        <font color="#FCE94F"><b>13.681s</b></font>
<font color="#AAAAAA">Ran all test suites.</font>
</pre>

Add serialize test for src/ride-hailing/NeedFilterParams.test.ts

---

src/drone-charging/NeedParams.test.ts

Create tests for _serialize_ and _deserialize_ for `src/drone-charging/NeedParams.ts` using Jest
Issue #97 
Increase the test coverage.
using 
> npm run jest
<pre><font color="#729FCF"><b>~/davFoundation/dav-js</b></font>$ npm run jest
&gt; dav-js@0.1.19 jest /home/abedo/davFoundation/dav-js
&gt; gulp jest
[<font color="#555753">21:27:09</font>] Using gulpfile <font color="#75507B">~/davFoundation/dav-js/gulpfile.js</font>
[<font color="#555753">21:27:09</font>] Starting &apos;<font color="#06989A">jest</font>&apos;...
<span style="background-color:#8AE234"><font color="#300A24"><b> PASS </b></font></span> src/drone-charging/<b>NeedParams.test.ts</b>
NeedParams class
serialize method
<font color="#4E9A06">✓</font> should return serialized NeedParams object with the current values (8ms) …

Add Serialize and deserialize methods to NeedParams.ts

---

src/drone-charging/NeedParams.test.ts

To run `npm run tslint` successfully as part of Travis
run `npm run tslint` successfully

Formatting test file
